name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    permissions:
      pages: write
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - name: Create .nojekyll file
        run: touch dist/.nojekyll

      - name: Copy .gitattributes
        run: cp .gitattributes dist/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: programminglife.io
          keep_files: false 